/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repository;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 * Finestra di dialogo per approfondire informazioni circa un autore specifico
 * @author davso
 */
public class AuthorCard extends javax.swing.JDialog {

    /**
     * Creates new form AuthorCard
     */
    public AuthorCard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /**
     * Metodo per settare il nome dell'Autore nella scheda di Approfondimento
     * @param name 
     */
    void setAuthorName(String name){
        authorNameLabel.setText(name);
    }
    /**
     * Metodo per settare il cognome dell'Autore nella scheda di Approfondimento
     * @param surname 
     */
    void setAuthorSurname(String surname){
        authorSurnameLabel.setText(surname);
    }
    /**
     * Metodo per settare l'email dell'Autore nella scheda di Approfondimento
     * @param email 
     */
    void setAuthorEmail(String email){
        authorEmailLabel.setText(email);
    }
    /**
     * Metodo che restituisce visivamente informazioni (progetti curati,
     * classi sviluppate etc.) di un autore
     * @param code Codice dell'autore
     */
    void showInformations(String code){
        showProjects(code);//Mostra i progetti curati
        showClasses(code);//Mostra le classi scritte
        showMethods(code);//Mostra i metodi scritti
        showTests(code);//Mostra i test sviluppati
        showCommits(code);//Mostra le modifiche in corso o chiuse
    }
    private void showProjects(String code){
        String query="SELECT P.* FROM PROGETTO P JOIN ASSEGNAZIONEPROGETTI A "
                + "ON P.NOME=A.NOMEPROGETTO WHERE CODAUTORE='"+code+"'";
        DefaultTableModel model= (DefaultTableModel)jFollowingProjectsTable.getModel();
        TableManager tm=new TableManager();
        tm.buildRowsCard(model,query,this);    
            
    }
    
    private void showClasses(String code){
        String query="SELECT DC.* FROM DESCRITTORE_CLASSE DC JOIN SCRITTURACLASSI SC "
                + "ON DC.CODDC=SC.CODCLASSE WHERE CODAUTORE='"+code+"'";
        DefaultTableModel model= (DefaultTableModel)jDevelopedClassesTable.getModel();
        TableManager tm=new TableManager();
        tm.buildRowsCard(model,query,this);    
            
    }
    private void showMethods(String code){
        String query="SELECT DM.* FROM DESCRITTORE_METODO DM JOIN SCRITTURAMETODO SM "
                + "ON DM.CODDM=SM.CODMETODO WHERE CODAUTORE='"+code+"'";
        DefaultTableModel model= (DefaultTableModel)jDevelopedMethodsTable.getModel();
        TableManager tm=new TableManager();
        tm.buildRowsCard(model,query,this);    
    }
    private void showTests(String code){
        String query="SELECT T.* FROM TEST T JOIN SCRITTURATEST ST "
                + "ON T.CODT=ST.CODTEST WHERE CODAUTORE='"+code+"'";
        DefaultTableModel model= (DefaultTableModel)jDevelopedTestsTable.getModel();
        TableManager tm=new TableManager();
        tm.buildRowsCard(model,query,this);    
    }
    private void showCommits(String code){
        String query="SELECT C.* FROM CHANGELOG C JOIN ASSEGNAZIONEMODIFICHE AM "
                + "ON C.CODL=AM.CODLOG WHERE CODAUTORE='"+code+"'";
        DefaultTableModel model= (DefaultTableModel)jAuthorCommitsTable.getModel();
        TableManager tm=new TableManager();
        tm.buildRowsCard(model,query,this);   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        AuthorCardTitlePanel = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        authorNameLabel = new java.awt.Label();
        authorSurnameLabel = new java.awt.Label();
        authorEmailLabel = new java.awt.Label();
        FollowingProjectsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jFollowingProjectsTable = new javax.swing.JTable();
        DevelopedClassesPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jDevelopedClassesTable = new javax.swing.JTable();
        DevelopedMethodsPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jDevelopedMethodsTable = new javax.swing.JTable();
        DevelopedTestsPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jDevelopedTestsTable = new javax.swing.JTable();
        AuthorCommitsPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jAuthorCommitsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Repository Software 1.0 - Scheda Autore");
        setMinimumSize(new java.awt.Dimension(1, 1));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1114, 975));

        jPanel2.setLayout(new java.awt.GridBagLayout());

        AuthorCardTitlePanel.setLayout(new java.awt.GridBagLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label1.setText("Scheda Autore");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 6;
        AuthorCardTitlePanel.add(label1, gridBagConstraints);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        label2.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        AuthorCardTitlePanel.add(label2, gridBagConstraints);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        label3.setText("Cognome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        AuthorCardTitlePanel.add(label3, gridBagConstraints);

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        label4.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        AuthorCardTitlePanel.add(label4, gridBagConstraints);

        authorNameLabel.setAlignment(java.awt.Label.CENTER);
        authorNameLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        authorNameLabel.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        AuthorCardTitlePanel.add(authorNameLabel, gridBagConstraints);

        authorSurnameLabel.setAlignment(java.awt.Label.CENTER);
        authorSurnameLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        authorSurnameLabel.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        AuthorCardTitlePanel.add(authorSurnameLabel, gridBagConstraints);

        authorEmailLabel.setAlignment(java.awt.Label.CENTER);
        authorEmailLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        authorEmailLabel.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        AuthorCardTitlePanel.add(authorEmailLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 0, 0);
        jPanel2.add(AuthorCardTitlePanel, gridBagConstraints);

        FollowingProjectsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Progetti Seguiti"));
        FollowingProjectsPanel.setMinimumSize(new java.awt.Dimension(100, 200));
        FollowingProjectsPanel.setPreferredSize(new java.awt.Dimension(300, 200));
        FollowingProjectsPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setMinimumSize(new java.awt.Dimension(600, 400));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 150));

        jFollowingProjectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome Progetto", "Path", "Data Creazione", "Descrizione", "Data Cancellazione"
            }
        ){public boolean isCellEditable(int row, int column){return false;}});
        jFollowingProjectsTable.setPreferredSize(new java.awt.Dimension(700, 400));
        jScrollPane2.setViewportView(jFollowingProjectsTable);

        FollowingProjectsPanel.add(jScrollPane2, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(FollowingProjectsPanel, gridBagConstraints);

        DevelopedClassesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Classi sviluppate"));
        DevelopedClassesPanel.setMinimumSize(new java.awt.Dimension(100, 200));
        DevelopedClassesPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane3.setMinimumSize(new java.awt.Dimension(600, 400));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(800, 150));

        jDevelopedClassesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ){public boolean isCellEditable(int row, int column){return false;}});
        jDevelopedClassesTable.setPreferredSize(new java.awt.Dimension(700, 400));
        jScrollPane3.setViewportView(jDevelopedClassesTable);

        DevelopedClassesPanel.add(jScrollPane3, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(DevelopedClassesPanel, gridBagConstraints);

        DevelopedMethodsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Metodi Sviluppati"));
        DevelopedMethodsPanel.setMinimumSize(new java.awt.Dimension(100, 200));
        DevelopedMethodsPanel.setPreferredSize(new java.awt.Dimension(100, 200));
        DevelopedMethodsPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane4.setMinimumSize(new java.awt.Dimension(600, 400));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(800, 150));

        jDevelopedMethodsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ){public boolean isCellEditable(int row, int column){return false;}});
        jDevelopedMethodsTable.setPreferredSize(new java.awt.Dimension(700, 400));
        jScrollPane4.setViewportView(jDevelopedMethodsTable);

        DevelopedMethodsPanel.add(jScrollPane4, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 100.0;
        jPanel2.add(DevelopedMethodsPanel, gridBagConstraints);

        DevelopedTestsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Test sviluppati"));
        DevelopedTestsPanel.setPreferredSize(new java.awt.Dimension(300, 200));
        DevelopedTestsPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane5.setMinimumSize(new java.awt.Dimension(600, 400));
        jScrollPane5.setPreferredSize(new java.awt.Dimension(800, 150));

        jDevelopedTestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ){public boolean isCellEditable(int row, int column){return false;}});
        jDevelopedTestsTable.setPreferredSize(new java.awt.Dimension(700, 400));
        jScrollPane5.setViewportView(jDevelopedTestsTable);

        DevelopedTestsPanel.add(jScrollPane5, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(DevelopedTestsPanel, gridBagConstraints);

        AuthorCommitsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Commit effettuati/in corso"));
        AuthorCommitsPanel.setPreferredSize(new java.awt.Dimension(300, 200));
        AuthorCommitsPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane6.setMinimumSize(new java.awt.Dimension(600, 400));
        jScrollPane6.setPreferredSize(new java.awt.Dimension(800, 150));

        jAuthorCommitsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ){public boolean isCellEditable(int row, int column){return false;}});
        jAuthorCommitsTable.setPreferredSize(new java.awt.Dimension(700, 400));
        jScrollPane6.setViewportView(jAuthorCommitsTable);

        AuthorCommitsPanel.add(jScrollPane6, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(AuthorCommitsPanel, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AuthorCardTitlePanel;
    private javax.swing.JPanel AuthorCommitsPanel;
    private javax.swing.JPanel DevelopedClassesPanel;
    private javax.swing.JPanel DevelopedMethodsPanel;
    private javax.swing.JPanel DevelopedTestsPanel;
    private javax.swing.JPanel FollowingProjectsPanel;
    private java.awt.Label authorEmailLabel;
    private java.awt.Label authorNameLabel;
    private java.awt.Label authorSurnameLabel;
    private javax.swing.JTable jAuthorCommitsTable;
    private javax.swing.JTable jDevelopedClassesTable;
    private javax.swing.JTable jDevelopedMethodsTable;
    private javax.swing.JTable jDevelopedTestsTable;
    private javax.swing.JTable jFollowingProjectsTable;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
