/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repository;

import javax.swing.table.DefaultTableModel;

/**
 * Finestra di dialogo per approfondire circa una classe specifica
 * @author davso
 */
public class ClassCard extends javax.swing.JDialog {

    /**
     * Creates new form ClassCard
     * @param parent
     * @param modal
     */
    public ClassCard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    void setClassName(String name){
        classNameLabel.setText(name);
    }
    /**
     * Metodo che restituisce visivamente informazioni di una classe
     * @param code Codice del descrittore classe 
     */
    
    void showInformations(String code){
        showClassReleases(code);//Mostra le versioni a cui la classe appartiene
        showClassAuthors(code);//Mostra gli autori della classe
        showClassChanges(code);//Mostra i commit che riguardano la classe
    }
    private void showClassReleases(String code){
        String query="SELECT C.CODC,R.VERSIONE,R.CODR,R.PATH,R.DATARILASCIO,"
                + "C.STATO FROM RELEASES R JOIN PACKAGES P "
                + "ON R.CODR=P.CODR JOIN CLASSE C ON P.CODP=C.CODP "
                + "WHERE C.CODDC='"+code+"'";
        DefaultTableModel model= (DefaultTableModel)jClassReleasesTable.getModel();
        TableManager tm=new TableManager();
        tm.buildRowsCard(model,query,this);    
            
    }
    private void showClassAuthors(String code){
        String query="SELECT A.* FROM AUTORE A JOIN SCRITTURACLASSI SC "
                + "ON A.CODA=SC.CODAUTORE WHERE SC.CODCLASSE='"+code+"'";
        DefaultTableModel model= (DefaultTableModel)jClassAuthorsTable.getModel();
        TableManager tm=new TableManager();
        tm.buildRowsCard(model,query,this);      
    }
    private void showClassChanges(String code){
        String query="SELECT CL.CODL,CL.TIPOMODIFICA,CL.DESCRIZIONE,CL.DATAAPERTURA,"
                + "CL.DATACHIUSURA FROM DESCRITTORE_CLASSE DC JOIN CLASSE C ON "
                + "DC.CODDC=C.CODDC JOIN CHANGELOG CL ON C.CODC=CL.CODC WHERE DC.CODDC='"
                +code+"'";
        DefaultTableModel model= (DefaultTableModel)jClassChangesTable.getModel();
        TableManager tm=new TableManager();
        tm.buildRowsCard(model,query,this);   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        ClassCardTitlePanel = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        classNameLabel = new java.awt.Label();
        ClassReleasesPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jClassReleasesTable = new javax.swing.JTable();
        ClassAuthorsPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jClassAuthorsTable = new javax.swing.JTable();
        ClassChangesPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jClassChangesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1, 1));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1114, 975));

        jPanel2.setLayout(new java.awt.GridBagLayout());

        ClassCardTitlePanel.setLayout(new java.awt.GridBagLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label1.setText("Scheda Classe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 6;
        ClassCardTitlePanel.add(label1, gridBagConstraints);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        label2.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        ClassCardTitlePanel.add(label2, gridBagConstraints);

        classNameLabel.setAlignment(java.awt.Label.CENTER);
        classNameLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        classNameLabel.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        ClassCardTitlePanel.add(classNameLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 0, 0);
        jPanel2.add(ClassCardTitlePanel, gridBagConstraints);

        ClassReleasesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Presente nelle versioni"));
        ClassReleasesPanel.setMinimumSize(new java.awt.Dimension(100, 200));
        ClassReleasesPanel.setPreferredSize(new java.awt.Dimension(300, 200));
        ClassReleasesPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setMinimumSize(new java.awt.Dimension(600, 400));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 150));

        jClassReleasesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome Progetto", "Path", "Data Creazione", "Descrizione", "Data Cancellazione"
            }
        ){public boolean isCellEditable(int row, int column){return false;}});
        jClassReleasesTable.setPreferredSize(new java.awt.Dimension(700, 400));
        jScrollPane2.setViewportView(jClassReleasesTable);

        ClassReleasesPanel.add(jScrollPane2, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(ClassReleasesPanel, gridBagConstraints);

        ClassAuthorsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Autori della classe"));
        ClassAuthorsPanel.setMinimumSize(new java.awt.Dimension(100, 200));
        ClassAuthorsPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane3.setMinimumSize(new java.awt.Dimension(600, 400));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(800, 150));

        jClassAuthorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ){public boolean isCellEditable(int row, int column){return false;}});
        jClassAuthorsTable.setPreferredSize(new java.awt.Dimension(700, 400));
        jScrollPane3.setViewportView(jClassAuthorsTable);

        ClassAuthorsPanel.add(jScrollPane3, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(ClassAuthorsPanel, gridBagConstraints);

        ClassChangesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Storico cambiamenti"));
        ClassChangesPanel.setPreferredSize(new java.awt.Dimension(300, 200));
        ClassChangesPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane6.setMinimumSize(new java.awt.Dimension(600, 400));
        jScrollPane6.setPreferredSize(new java.awt.Dimension(800, 150));

        jClassChangesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ){public boolean isCellEditable(int row, int column){return false;}});
        jClassChangesTable.setPreferredSize(new java.awt.Dimension(700, 400));
        jScrollPane6.setViewportView(jClassChangesTable);

        ClassChangesPanel.add(jScrollPane6, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 100.0;
        jPanel2.add(ClassChangesPanel, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClassAuthorsPanel;
    private javax.swing.JPanel ClassCardTitlePanel;
    private javax.swing.JPanel ClassChangesPanel;
    private javax.swing.JPanel ClassReleasesPanel;
    private java.awt.Label classNameLabel;
    private javax.swing.JTable jClassAuthorsTable;
    private javax.swing.JTable jClassChangesTable;
    private javax.swing.JTable jClassReleasesTable;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
