/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repository;
import javax.swing.table.DefaultTableModel;

/**
 * Finestra di dialogo per approfondire circa un progetto
 * @author davso
 */
public class ProjectCard extends javax.swing.JDialog {

    /**
     * Creates new form ProjectCard
     * @param parent
     * @param modal
     */
    public ProjectCard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    void setProjectName(String name){
        ProjectNameLabel.setText(name);
    }
    /**
     * Metodo che restituisce visivamente le informazioni di un progetto
     * @param name Nome del progetto
     */
    void showInformations(String name){
        showProjectReleases(name);//Mostra le varie release del progetto
        showDevelopmentTeam(name);//Mostra il team di sviluppo
    }
    private void showProjectReleases(String name){
        String query="SELECT R.VERSIONE,R.PATH,R.DATARILASCIO,R.CODR FROM RELEASES R JOIN PROGETTO P "
                + "ON R.NOMEPROGETTO=P.NOME WHERE NOME='"+name+"'";
        DefaultTableModel model= (DefaultTableModel)jProjectReleasesTable.getModel();
        TableManager tm=new TableManager();
        tm.buildRowsCard(model,query,this);     
            
    }
    private void showDevelopmentTeam(String name){
        String query="SELECT A.* FROM AUTORE A JOIN ASSEGNAZIONEPROGETTI AP "
                + "ON A.CODA=AP.CODAUTORE WHERE NOMEPROGETTO='"+name+"'";
        DefaultTableModel model= (DefaultTableModel)jDevelopmentTeamTable.getModel();
        TableManager tm=new TableManager();
        tm.buildRowsCard(model,query,this);   
            
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        ProjectCardTitlePanel = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        ProjectNameLabel = new java.awt.Label();
        ProjectReleasesPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jProjectReleasesTable = new javax.swing.JTable();
        TeamDevelopmentPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jDevelopmentTeamTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Repository Software 1.0 - Scheda Progetto");
        setMinimumSize(new java.awt.Dimension(1, 1));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1114, 975));

        jPanel2.setLayout(new java.awt.GridBagLayout());

        ProjectCardTitlePanel.setLayout(new java.awt.GridBagLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label1.setText("Scheda Progetto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 6;
        ProjectCardTitlePanel.add(label1, gridBagConstraints);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        label2.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        ProjectCardTitlePanel.add(label2, gridBagConstraints);

        ProjectNameLabel.setAlignment(java.awt.Label.CENTER);
        ProjectNameLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ProjectNameLabel.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        ProjectCardTitlePanel.add(ProjectNameLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 0, 0);
        jPanel2.add(ProjectCardTitlePanel, gridBagConstraints);

        ProjectReleasesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Releases"));
        ProjectReleasesPanel.setMinimumSize(new java.awt.Dimension(100, 200));
        ProjectReleasesPanel.setPreferredSize(new java.awt.Dimension(300, 200));
        ProjectReleasesPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setMinimumSize(new java.awt.Dimension(600, 400));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 150));

        jProjectReleasesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome Progetto", "Path", "Data Creazione", "Descrizione", "Data Cancellazione"
            }
        ){public boolean isCellEditable(int row, int column){return false;}});
        jProjectReleasesTable.setPreferredSize(new java.awt.Dimension(700, 400));
        jScrollPane2.setViewportView(jProjectReleasesTable);

        ProjectReleasesPanel.add(jScrollPane2, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(ProjectReleasesPanel, gridBagConstraints);

        TeamDevelopmentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Team di Sviluppo"));
        TeamDevelopmentPanel.setMinimumSize(new java.awt.Dimension(100, 200));
        TeamDevelopmentPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane3.setMinimumSize(new java.awt.Dimension(600, 400));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(800, 150));

        jDevelopmentTeamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ){public boolean isCellEditable(int row, int column){return false;}});
        jDevelopmentTeamTable.setPreferredSize(new java.awt.Dimension(700, 400));
        jScrollPane3.setViewportView(jDevelopmentTeamTable);

        TeamDevelopmentPanel.add(jScrollPane3, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(TeamDevelopmentPanel, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProjectCardTitlePanel;
    private java.awt.Label ProjectNameLabel;
    private javax.swing.JPanel ProjectReleasesPanel;
    private javax.swing.JPanel TeamDevelopmentPanel;
    private javax.swing.JTable jDevelopmentTeamTable;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable jProjectReleasesTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
