/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repository;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * Finestra di dialogo per impostare i parametri di connessione al DataBase.
 *
 * @author davso
 * @version 2019
 */
public class Welcome extends javax.swing.JDialog {
    /**
     * Costante per indicare la pressione del pulsante Annulla.
     */
    public static final int PREMUTO_ANNULLA = 0;
    /**
     * Costante per indicare la pressione del pulsante OK.
     */
    public static final int PREMUTO_LOGIN = 1;
    
    private int premuto; // registra quale pulsante viene premuto

  
    /**
     * Creates new form Welcome
     * @param parent
     * @param modal
     */
    
    public Welcome(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        /*
        * WindowListener è un'interfaccia che "ascolta" gli eventi relativi ad 
        * una finestra.Associamo a Welcome un oggetto della classe WindowAdapter
        * che implementa WindowListener.
        */
        this.addWindowListener(new java.awt.event.WindowAdapter(){
        @Override
        //Overriding del metodo che gestisce la chiusura della finestra
        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
        if (JOptionPane.showConfirmDialog(Welcome.this, 
            "Sei sicuro di voler chiudere questa finestra?", "Chiusura finestra", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION)
        {
            dispose();
            System.exit(0);
        }
        }
        });
        
        
    }
    public int getPremuto() {
       return premuto;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        label1 = new java.awt.Label();
        LoginUI = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        userField = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        passwordField = new javax.swing.JPasswordField();
        jStartButton = new javax.swing.JButton();
        hostField = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        portField = new javax.swing.JTextField();
        label6 = new java.awt.Label();
        servizioField = new javax.swing.JTextField();
        label7 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Welcome - Repository Software 1.0");
        setLocation(new java.awt.Point(400, 400));
        setPreferredSize(new java.awt.Dimension(300, 400));
        setSize(new java.awt.Dimension(400, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label1.setText("Repository Software");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 12, 0);
        getContentPane().add(label1, gridBagConstraints);
        label1.getAccessibleContext().setAccessibleName("WelcomeText");

        LoginUI.setLayout(new java.awt.GridBagLayout());

        label3.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        label3.setName(""); // NOI18N
        label3.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 54);
        LoginUI.add(label3, gridBagConstraints);

        userField.setText("user");
        userField.setToolTipText("");
        userField.setName(""); // NOI18N
        userField.setPreferredSize(new java.awt.Dimension(100, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        LoginUI.add(userField, gridBagConstraints);

        label4.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        label4.setName(""); // NOI18N
        label4.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 53);
        LoginUI.add(label4, gridBagConstraints);

        passwordField.setText("password");
        passwordField.setPreferredSize(new java.awt.Dimension(100, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        LoginUI.add(passwordField, gridBagConstraints);

        jStartButton.setText("Entra");
        jStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 0, 4);
        LoginUI.add(jStartButton, gridBagConstraints);

        hostField.setText("localhost");
        hostField.setToolTipText("");
        hostField.setName(""); // NOI18N
        hostField.setPreferredSize(new java.awt.Dimension(100, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        LoginUI.add(hostField, gridBagConstraints);

        label5.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        label5.setName(""); // NOI18N
        label5.setText("Host");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 75);
        LoginUI.add(label5, gridBagConstraints);

        portField.setText("1521");
        portField.setToolTipText("");
        portField.setName(""); // NOI18N
        portField.setPreferredSize(new java.awt.Dimension(100, 23));
        portField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        LoginUI.add(portField, gridBagConstraints);

        label6.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        label6.setName(""); // NOI18N
        label6.setText("Porta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 75);
        LoginUI.add(label6, gridBagConstraints);

        servizioField.setText("xe");
        servizioField.setToolTipText("");
        servizioField.setName(""); // NOI18N
        servizioField.setPreferredSize(new java.awt.Dimension(100, 23));
        servizioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servizioFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        LoginUI.add(servizioField, gridBagConstraints);

        label7.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        label7.setName(""); // NOI18N
        label7.setText("Servizio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 62);
        LoginUI.add(label7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(LoginUI, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartButtonActionPerformed
        DBManager.host = hostField.getText();
        try {
            DBManager.porta = Integer.parseInt(portField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La porta dev'essere"
                + " un numero", "Errore", JOptionPane.ERROR_MESSAGE);
        }
        
        DBManager.servizio = servizioField.getText();
        DBManager.user = userField.getText();
        DBManager.password = new String(passwordField.getPassword());
        try {
            DBManager.setDefaultConnection(DBManager.nuovaConnessione());
            premuto = PREMUTO_LOGIN;
            dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Connessione fallita (credenziali"
                + " errate?)", "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jStartButtonActionPerformed

    private void portFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portFieldActionPerformed

    private void servizioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servizioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servizioFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginUI;
    private javax.swing.JTextField hostField;
    private javax.swing.JButton jStartButton;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField portField;
    private javax.swing.JTextField servizioField;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
